= Formulas
:stem: latexmath
:source-highlighter: pygments
:pygments-style: monokai
:wrap: normal

* Dot Product

[stem]
++++
\overrightarrow{a} \cdot \overrightarrow{b} \\
\left[ \begin{array}{c}
a_{1} \\
a_{2} \\
\vdots \\
a_{n}
\end{array} \right]

\cdot

\left[ \begin{array}{c}
b_{1} \\
b_{2} \\
\vdots \\
b_{n}
\end{array} \right]
=
a_{1} * b_{1} + a_{2} * b_{2} + * a_{n} * b_{n}
++++

* Circle Overlapping

[stem]
++++
|\overrightarrow{c_1} \cdot \overrightarrow{c_2}| <= r_1 + r_2
++++

NOTE: stem:[c_1] and stem:[c_1] are the centers of circle one and two

* Pythagrean Thereom to find distancce between balls centers

[stem]
++++
a^2 + b^2 = c^2
++++

* Vector Normalization

[stem]
++++
\hat{u} = \frac{\overrightarrow{v}}{|\overrightarrow{v}|}
++++


* Magnitude of a Vector

[stem]
++++
|\overrightarrow{a}| = \sqrt{a_{1}^2 + a_{2}^2 + \dots a_{n}^2}
++++

* Finding tangent vector

[stem]
++++
x = -y, y = x
++++

* 1D Conservation of Momentum

[stem]
++++
m_1 v_1 + m_2 v_2 = m_1 v_1 + m_2 v_2
++++

* 1D Elastic Collision

[stem]
++++
v_1' = (v_1 * (m_1-m_2) + 2 * m_2 * v_2)) / (m_1 + m_2) \\
v_2' = (v_2 * (m_2-m_1) + 2 * m_1 * v_1)) / (m_1 + m_2)
++++

* Finding magnitude in a specific direction

[stem]
++++
|\overrightarrow{v}| = \overrightarrow{n} \cdot \overrightarrow{v}
++++

* Distinct unordered pairs

[stem]
++++
(n,2) = \frac{n(n-1)}{2}]
++++


== Seeing if circle collide
Instead of doing this:

[source,c]
----
sqrtf((x1 - x2)*(x1 - x2) + (y1 - y2)*(y1 - y2)) <= (r1 + r2);
----

We can save some computing speed by removing the square root and just
multiplying the left side by itself:

[source,c]
----
fabs((x1 - x2)*(x1 - x2) + (y1 - y2)*(y1 - y2)) <= (r1 + r2)*(r1 + r2);
----

== Clamping Velocity

We can use the dot product to find the velocity in specific direction and then
clamp it

[source,c]
----
if (fabs(ball.vx*ball.vx + ball.vy*ball.vy) < 0.01f)
----
